<h1>Exercise 5</h1>
TKO_7093 Statistical Data Analysis

In [83]:
import pandas as pd 
import scipy
from scipy import stats
import numpy as np

<h2>1.</h2>
Load the data available in the file 51-data.csv.<br><br>

1. Find invalid values in the data and replace them either with a correct value (if possible) or with NaN.<br>
2. Replace all missing values of the purchases variable with zero.<br>
3. Use median imputation to fill in all missing values of the retention_time variable.<br>
(BONUS) Group the observations by sex and location before calculating the substitute median(s).

In [93]:
loc = r'C:\Users\peppi\Desktop\lipasto\statisticalDataAnalysis\51-data.csv'
df = pd.read_csv(loc, sep=",", na_values="NA", header=0)

        sex  location  purchases  retention_time
0    female  Helsinki        7.0            57.1
1    female  Helsinki        5.0             NaN
2    female     Turku        8.0            50.6
3      male  Helsinki        5.0            31.7
4    female  Helsinki        2.0           120.0
..      ...       ...        ...             ...
195    male     Turku        3.0            40.5
196    male  Helsinki        3.0            36.9
197  female  Helsinki        6.0            59.2
198    male  Helsinki        5.0            31.8
199  female  Helsinki        6.0           181.9

[200 rows x 4 columns]

In [161]:
# 1.1
df['purchases'] = df['purchases'].fillna(0)
df.loc[df.location == '33100', 'location'] = 'Tampere'
df.loc[df.location == '20100', 'location'] = 'Turku'
# df.loc[df.retention_time < 0, 'retention_time'] = np.nan
df.describe()

TypeError: '<' not supported between instances of 'str' and 'int'

In [22]:
# 1.3
df['retention_time'] = df['retention_time'].fillna((df['retention_time'].median()))
df

        sex  location  purchases  retention_time
0    female  Helsinki        7.0            57.1
1    female  Helsinki        5.0            32.9
2    female     Turku        8.0            50.6
3      male  Helsinki        5.0            31.7
4    female  Helsinki        2.0           120.0
..      ...       ...        ...             ...
195    male     Turku        3.0            40.5
196    male  Helsinki        3.0            36.9
197  female  Helsinki        6.0            59.2
198    male  Helsinki        5.0            31.8
199  female  Helsinki        6.0           181.9

[200 rows x 4 columns]

<h2>2.</h2>
Load the file GDS5037.soft (see the exercise 4.3) and filter the data such that it only contains the probe ids listed in the file 52-probes.ids and the subject ids listed in the files 52-control.ids and 52-asthma.ids.<br><br>

1. Create a box plot of gene expression levels for each subject. Do you notice visible differences between the subjects or between the groups?

2. Use a T-test to find differentially expressed genes (i.e. probes for which the means are different between the control and asthma groups). Adjust the p-values with the Benjamini-Hochberg method.

3. Create histograms of the unadjusted and adjusted p-values. Why do these two histograms differ?

4. How many differentially expressed genes (i.e. statistically significant differences) are there at the false discovery rate of 0.05?

5. Sort the adjusted p-values in ascending order. Which genes do the first ten probes correspond to?

In [154]:
# 2.1
soft = pd.read_csv('GDS5037.soft', sep="\s+" ,header=160, skipfooter=1, engine='python')
df_soft = pd.DataFrame(soft)
df_soft = df_soft.set_index('ID_REF')

In [140]:
# choose based on files
probes = pd.read_table('52-probes.ids', header=None)[0]
controls = pd.read_table('52-control.ids', header=None)[0]
asthma = pd.read_table('52-asthma.ids', header=None)[0]
subjects = pd.concat([controls, asthma])

df_full = df_soft.loc[probes,subjects]
df_full

,GSM1068458,GSM1068459,GSM1068460,GSM1068461,GSM1068462,GSM1068463,GSM1068464,GSM1068465,GSM1068466,GSM1068467,...,GSM1068556,GSM1068557,GSM1068558,GSM1068559,GSM1068560,GSM1068561,GSM1068562,GSM1068563,GSM1068564,GSM1068565
ID_REF,,,,,,,,,,,,,,,,,,,,,
A_23_P100355,9.73450,9.82071,10.38230,10.43700,10.37030,10.59030,10.48990,10.76750,10.57110,9.91477,...,10.94870,10.28070,10.21060,10.48320,10.67700,10.76620,10.75330,10.59410,10.63990,10.53500
A_23_P101829,7.34121,8.00249,7.17964,7.53055,7.10362,7.07410,6.69177,7.37524,7.49978,7.34268,...,7.18555,7.18596,7.50311,7.61950,7.35386,7.63585,7.29750,7.18897,7.11162,7.49630
A_23_P102235,12.12020,12.31900,12.42870,12.23300,12.14920,12.22640,12.16290,12.19920,12.26940,12.09810,...,12.28210,12.28820,12.29720,12.35510,12.30030,12.24170,12.40860,12.05510,12.23110,12.02790
A_23_P102607,7.07051,6.91728,7.16459,6.19421,6.86695,6.84001,7.34184,7.09113,6.87948,6.67208,...,7.20520,7.04128,6.85812,6.87079,7.12792,6.55122,6.75280,7.29706,7.01142,6.79003
A_23_P102743,7.31329,6.38099,7.14409,6.72997,7.03673,6.75132,6.62888,6.63785,6.87825,6.71155,...,6.98354,7.11257,6.91354,7.21952,6.96467,6.99149,6.88292,6.80598,7.04567,6.81248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A_32_P80255,9.72013,9.20204,8.81502,9.55290,9.88867,9.22377,9.70530,9.14508,9.19637,9.92583,...,9.53174,9.59771,9.75629,9.44850,9.54217,9.48188,9.00412,9.22302,9.81349,9.51958
A_32_P83784,9.33227,8.47086,9.01771,9.30044,8.65403,8.70030,8.26453,8.52626,8.62973,8.91668,...,8.59478,8.24108,8.50516,8.47277,8.62158,8.80231,8.72801,8.87190,8.61916,8.55743
A_32_P902988,6.90708,8.63739,6.96754,7.68574,8.46000,8.44160,9.05813,9.64739,7.50242,9.80580,...,8.96406,9.65092,12.11820,8.48703,9.87380,11.01930,10.15100,8.71636,11.18370,9.48001
A_32_P9368,8.16925,9.71353,8.21237,8.02641,8.57337,8.79693,8.34014,8.47326,8.50564,7.63345,...,9.18419,8.49307,8.35604,8.17409,8.65650,9.05695,8.54015,8.81673,8.84424,8.31765
A_32_P96807,10.32810,9.57402,10.16880,9.97312,10.22750,9.10535,10.10640,9.90884,10.21520,9.99832,...,9.76844,9.80273,9.44613,9.55091,9.72005,9.83834,9.61187,9.79608,9.76633,9.68503

In [155]:
# Use a T-test to find differentially expressed genes (i.e. probes for which the means are different between the control and asthma groups). 
# Adjust the p-values with the Benjamini-Hochberg method.
df_control = df_full.loc[:,controls]
df_asthma = df_full.loc[:,asthma]

dft = pd.DataFrame(columns=['result_of_t-test'], index=[df_control.index])
for ind in df_control.index:
    dft.at[ind, 'result_of_t-test'] = stats.ttest_ind( df_control.loc[ind, :], df_asthma.loc[ind, :] ).pvalue
    
newdf = dft.sort_values(by='result_of_t-test')
ids = newdf.head(10).index.values
for id in ids:
    print(df_soft.loc[id].IDENTIFIER)

SYT4
CCL15
BMP7
DHX37
BMP2K
PLPP6
SNTG2
RORA
NBL1
PARM1

<h2>3.</h2>
Load the data available in the file 53-data.csv, which contains daily numbers of cyclists spotted on selected streets.<br><br>

For each weekday (Monday - Sunday), calculate the mean daily number of cyclists for each street. Plot the means as a bar plot.<br><br>

For each month (January - December), calculate the mean daily number of cyclists for each street. Plot the means as a bar plot.<br><br>

Calculate the Spearman's correlation coefficient and create a scatter plot for each pair of streets.<br><br>

What information do these plots reveal?<br><br>

<h2>4.</h2>
An advertisement company followed online customers to discover how effectively advertisements lure them to spend money. The data files 54-image.csv and 54-video.csv contain information on how much customers spent in total after clicking on advertisements.<br><br>

Is there statistical evidence to claim that the total amount spent by customers is different if they click on image advertisements than on video advertisements?